export {
  ElevenLabsProvider,
  elevenLabsProvider,
  KNOWN_VOICES,
  resolveVoiceId,
  type Voice,
  type TTSOptions,
  type TTSResult,
  type MusicOptions,
  type MusicResult,
  type SoundEffectOptions,
  type SoundEffectResult,
  type AudioIsolationResult,
  type VoiceCloneOptions,
  type VoiceCloneResult,
} from "./ElevenLabsProvider.js";
